# backward compatibility shim
from bankrot_bot.keyboards.menus import (
    main_menu_kb,
    start_ikb,
    home_ikb,
    profile_ikb,
    cases_list_ikb,
    case_card_ikb,
    docs_home_ikb,
    help_ikb,
    help_item_ikb,
    docs_menu_ikb,
    case_files_ikb,
    case_archive_ikb,
    cases_menu_ikb,
    my_cases_ikb,
    docs_catalog_ikb,
    docs_category_ikb,
    docs_item_ikb,
    case_parties_ikb,
    party_view_ikb,
    case_assets_ikb,
    asset_view_ikb,
)
